### ISSUE TITLE
[C Mini-Project] Select Title

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/C_v3#1]
# Select Project Title
Comment down your project title & group member name. Do not repeat the project.

- [x] Student Mgmt. System, 
- [x] Employee Mgmt. System, 
- [x] Library System, 
- [x] eAttendance Mgmt. System, 
- [ ] Pharmacy Mgmt. System, 
- [x] Blood Bank Mgmt. System, 
- [ ] Kitchen Recipie
- [ ] Workers’ Time Logger
- [x] Hospital Mgmt. System, 
- [x] Hotel Reservation System, 
- [ ] Inventory Mgmt. System, 
- [x] Canteen Billing System, 
- [ ] Task Reminder 
- [ ] Number Plate Registration System, 
- [ ] Tax Payment System, 
- [x] eWallet, 
- [x] Mini-Mart Billing System, 
- [ ] Tourist Entry Logger, 
- [ ] Feedback Mgmt. System, 
- [ ] Project Info. System,
- [x] Khwopa Quiz
- [ ] Class Routine Mgmt. System
- [x] Bank Mgmt. System
- [ ] Student Payroll System
- [ ] Break-Game
- [x] Land Converter
- [ ] Prescription Log
- [x] Tic-tac-toe
- [x] Bag Chal
- [ ] Hostel Mgmt. System
- [x] Date Converter
- [x] Marksheet Generator
- [x] Hangman
- [x] Scientific Calculator
- [x] Telephone Directory
- [x] eVoting
- [ ] Puzzle
- [ ] Data Encryption/Decryption
- [ ] Data Compression

Finalize your project title …

**Comment by SKarmaa** [comment]
Title: Crop suggestion and wiki
Shopnil Shrestha
Bijay Kadariya
Jenis Twayna
Prajwal Acharya

**Comment by Pradyum55** [comment]
Pradyum chandra jha 
Rajendra kasula
Prabin oli 
Saphal paudel 
Project name :- canteen biling system

**Comment by AsimBhadra** [comment]
**Project title: Scientific Calculator**
Ankit Kayastha
Rahul Khatri
Bikesh Manandhar
Ashim Bhadra

**Comment by AxD99999** [comment]
Asutosh K. Sedai
Bigyan Thapa
Sankalpa Kandel
Arun Prasad Paneru

Project name: eWallet

**Comment by DivasRegmi** [comment]
Project name = Bag chal    (BCT)

Dibas Regmi
Pawan Dhungana
shreyesh Dhakal
sushil Sharma.

**Comment by ManeesRj150** [comment]
Project name= land converter
Aashish Thapa
Agreem Thapa
Manish Rajbahak 
Subin Shrestha

**Comment by Shresthaanish713** [comment]
project name- marksheet generator
team:
Anish Shrestha
Bishal Bhatt
Pragya Shrestha
Suyan Shrestha

**Comment by abhishek-hyangol** [comment]
project name- Bank management system
Team:
Safal Raj Manandhar
Abhishek Hyangol
Amit Shrestha
Anuj Gaida

**Comment by ShresthaPrajwal** [comment]
Project Name: Snake
Participants;
-Aayush Dahal
-Niru Dhaubanjar
-Prajwal Shrestha
-Sameer Shrestha

**Comment by Arogyadh** [comment]
Project Name: Student Management System
Praticipants :
-Arogya Dhaubhadel
-Aaju Prajapati
-Indira Kasichhwa
-Shristi Koju

**Comment by puzancozzu** [comment]
Title: Resturant Billing System 
 
Team :
Rajat Shrestha-30
Rocky Suwal -31 
Poojan Koju-23 
Sharad Mishra-41

**Comment by romikgosai** [comment]
Project Name : Mini Mart Billing System

Rabit Khaitu - 28
Romik Gosai - 32
Sagar Suwal - 34
Saman Chauguthi - 35

**Comment by bhimlopchan** [comment]
Project Name: Hotel Reservation System
BEL 2076 
Bhim Lopchan Tamang: 8
Dikshit Karki: 14
Jagrit Parajuli: 15
Rohit Dangol: 34
