### ISSUE TITLE
Generate Patterns

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/C_v3#6]
Control as per String Length:
![NepaL](https://user-images.githubusercontent.com/5508421/74015876-94a77000-49b9-11ea-832d-575b4e5e544c.PNG)
- [Source Code](https://github.com/ErSKS/C_v3/blob/master/NepaL.c)

**Comment by ErSKS** [comment]
Use unformatted functions:
![PAT_1_2 Programming](https://user-images.githubusercontent.com/5508421/74018550-3a5cde00-49be-11ea-9b87-7e0bb00ab800.PNG)

**Comment by ErSKS** [comment]
![Pattern11_A](https://user-images.githubusercontent.com/5508421/74018598-4f397180-49be-11ea-8fb1-db7b2b216d20.PNG)

**Comment by ErSKS** [comment]
![Pattern22](https://user-images.githubusercontent.com/5508421/74018632-5b253380-49be-11ea-86c0-b90b998d8cf6.PNG)

**Comment by ErSKS** [comment]
![Pattern20](https://user-images.githubusercontent.com/5508421/74018684-6bd5a980-49be-11ea-8015-a205c74dc936.PNG)

**Comment by ErSKS** [comment]
![Pattern21](https://user-images.githubusercontent.com/5508421/74018695-7132f400-49be-11ea-99f6-a408265560d6.PNG)

**Comment by ErSKS** [comment]
![Pattern21_2](https://user-images.githubusercontent.com/5508421/74018712-78f29880-49be-11ea-90e3-2b183e1262b7.PNG)

**Comment by Znis** [comment]
> Use unformatted functions:
> ![PAT_1_2 Programming](https://user-images.githubusercontent.com/5508421/74018550-3a5cde00-49be-11ea-9b87-7e0bb00ab800.PNG)
//General program to print output in given pattern (string to be fetched by user)
`#include<stdio.h>
#include<conio.h>
#include<string.h>
int main(){
int i, j;
char np[100];
puts("Enter any string having odd number of letters :");
gets(np);
puts("");

for(i=0;i<((strlen(np)+1)/2);i++){
	for(j=i;j<(strlen(np))-i;j++){
		putchar(np[j]);

	}
	puts("");
}
getch();
	return 0;
}
`

**Comment by Znis** [comment]
//General program for PATTERN 11 (number of rows to be fetched by user)
`#include<stdio.h>
int main(){
	int i,j,k,l,m,c,d,n;
	d=1;
	agai:
	printf("Enter the number of rows for pattern you want to display (MUST BE AN ODD NUMBER): ");
	scanf("%d",&n);
	if (n%2==1){
printf("\n PATTERN 11\n");
	c=n-2;
	for(i=1;i<=n;i++){

		if(i<=(n/2+1)){
		for(j=i;j<=n/2;j++)
		printf(" ");
		for(k=1;k<=i*2-1;k++)
		printf("+");
	}else{
		for(l=1;l<=d;l++)
		printf(" ");
		if(d<=n/2)
		d++;
		for(m=c;m>=1;m=m-1)
		printf("+");
		c=c-2;
	}
	printf("\n");
	}
}else{
	printf("!!EVEN NUMBER IS INVALID!! PLEASE RE-ENTER THE ODD NUMBER\n");
	goto agai;
}
	return 0;
}`

**Comment by Znis** [comment]
`//General program of pattern 22(fibonacci) (number of rows to be fetched by user)
#include<stdio.h>
#include<conio.h>

int main(){
int i, j,n,a,b,c;
a=0;
b=0;
printf("Enter number of rows to print fibonacci series: ");
scanf("%d",&c);
printf("\n");

for(i=1;i<=c;i++){
        for(j=1;j<=i;j++){
n=a+b;
  printf(" %d",n);
a=b;
b=n;
        }
if(b==0)
a=1;

printf("\n");
}
getch();
return 0;
}
`

**Comment by Znis** [comment]
`//General program for pattern21
#include<stdio.h>
#include<string.h>
int main(){
char a[100];
int i,j,k=0,l;
printf("Enter the number of 1's and 0's. (The number should have odd number of letters) :");
scanf("%s",a);
l=strlen(a)-1;
printf("\n");
for(i=1;i<=strlen(a);i++){
        if(i<=((strlen(a)+1)/2)){

    for(j=0;j<strlen(a);j++){
        if (j<=k){
            printf("%c ",a[j]);
        }else if(j>=l){
        printf("%c ",a[j]);
        }else printf("  ");
    }
k=k+1;
l=l-1;
printf("\n");
}

else{

    for(j=0;j<=strlen(a)-1;j++){
        if (j>=k){
            printf("%c ",a[j]);
        }else if(j<=l){
        printf("%c ",a[j]);
        }else printf("  ");
    }

k=k+1;
l=l-1;
printf("\n");
}
}
getch();
return 0;
}




`
