### ISSUE TITLE
Submit Assignment#3 [Deadline: Falgun 9, 2076]

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/C_v3#7]
- [Assignment#3](https://github.com/ErSKS/C_v3/blob/master/Assignment_3.pdf)

**Comment by samratpradhan** [comment]
![received_587965148448339](https://user-images.githubusercontent.com/58108207/74086640-d82ed680-4aac-11ea-8179-3b27ea38779c.jpeg)
![received_880333569061772](https://user-images.githubusercontent.com/58108207/74086646-e7ae1f80-4aac-11ea-841d-94d364944717.jpeg)
