### ISSUE TITLE
Employee Details - Sort by Salary in Ascending Order

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/C_v3#9]
![EMP_SortBy_Sal](https://user-images.githubusercontent.com/5508421/74214536-e73ca100-4cc5-11ea-902f-2e7e7466d740.PNG)

[Source Code](https://github.com/ErSKS/C_v3/blob/master/EMP_SortBy_Sal.C)

**Q**. WAP to sort stored student information from their names in ascending order. The structure to hold information is **_Student_** which have members _name_, _crn_, _age_, _gender_. Ask the user to enter _n_ no. of information then store it to structure and save it to file name given by the user. Display the sorted list with full information.

Comment down your code:

**Comment by bijay191** [comment]
#include<stdio.h>
#include<conio.h>
void main(){
	struct student{
	char name[20];
	int crn;
	int age;
	char gender[6];
	};
	int n;

struct student s[100],temp;
int i,j,k;
FILE *fp;
clrscr();
printf("\nEnter how many records you want to enter : ");
scanf("%d",&n);
fp=fopen("student.txt","w+b");
for(i=0;i<n;i++){
	printf("Enter Name, Roll no, Age & Gender of student %d: ",i+1);
	scanf("%s%d%d%s",s[i].name,&s[i].crn,&s[i].age,s[i].gender);
}
for(i=0;i<n;i++){
	for(j=i+1;j<n;j++){
		if(strcmp(s[i].name,s[j].name)>0){
		temp=s[i];
		s[i]=s[j];
		s[j]=temp;
		}
	}
fwrite(&s,sizeof(s),("(%d)",n),fp);
rewind(fp);
fread(&s,sizeof(s),("(%d)",n),fp);

printf("\nSorted (by names):\n");
for(i=0;i<n;i++){
	printf("Name : %-10sRoll no : %-4dAge : %-3dGender : %-2s\n",s[i].name,s[i].crn,s[i].age,s[i].gender);
	}
	fclose(fp);
	}
	getch();
}



![IMG_20200218_165233](https://user-images.githubusercontent.com/58539186/74793801-8d516200-52e9-11ea-87b6-6f89ea5e2a8e.jpg)

**Comment by bijay191** [comment]
#include<stdio.h>
#include<conio.h>
#include<string.h>
void main(){
	struct student{
	char name[20];
	int crn;
	int age;
	char gender[6];
	};
	int n;
struct student s[100],temp;
int i,j,k;
FILE *fp;
clrscr();
printf("\nEnter how many records you want to enter : ");
scanf("%d",&n);
fp=fopen("student.txt","w+b");
for(i=0;i<n;i++){
	printf("Enter Name, Roll no, Age & Gender of student %d: ",i+1);
	scanf("%s%d%d%s",s[i].name,&s[i].crn,&s[i].age,s[i].gender);
}
for(i=0;i<n-1;i++){
	for(j=i+1;j<n;j++){
		if(strcmp(s[i].name,s[j].name)>0){
		temp=s[i];
		s[i]=s[j];
		s[j]=temp;
		}
	     }
	}
fwrite(&s,sizeof(s),("(%d)",n),fp);
rewind(fp);
fread(&s,sizeof(s),("(%d)",n),fp);
printf("\nSorted (by names):\n");
for(i=0;i<n;i++){
	printf("Name : %-10sRoll no : %-4dAge : %-3dGender : %-2s\n",s[i].name,s[i].crn,s[i].age,s[i].gender);
	}
	fclose(fp);
	getch();
}



![Screenshot (9)](https://user-images.githubusercontent.com/58539186/74847773-c5dd5400-535a-11ea-9908-e49a9ead2106.png)

**Comment by valar-morghulis-end** [comment]
#include<stdio.h>
#include<conio.h>
#include<string.h>
void main(){
struct student{
char name[20];
int roll;
int age;
char gender[6];
};
int n;
struct student s[100],temp;
int i,j,k;
FILE *file;
printf("\nEnter how many records you want to enter : ");
scanf("%d",&n);
file=fopen("record.txt","w+");
for(i=0;i<n;i++){
printf("Enter Name,class Roll no, Age & Gender of student %d: ",i+1);
scanf("%s%d%d%s",s[i].name,&s[i].roll,&s[i].age,s[i].gender);
}
for(i=0;i<n-1;i++){
for(j=i+1;j<n;j++){
if(strcmp(s[i].name,s[j].name)>0){
temp=s[i];
s[i]=s[j];
s[j]=temp;
}
}
}
fwrite(&s,sizeof(s),("(%d)",n),file);
rewind(file);
fread(&s,sizeof(s),("(%d)",n),file);
printf("\nSorted (by names):\n");
for(i=0;i<n;i++){
printf("Name : %-11sRoll no : %-5dAge : %-4dGender : %-3s\n",s[i].name,s[i].roll,s[i].age,s[i].gender);
}
fclose(file);
getch();
}

**Comment by valar-morghulis-end** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/58299923/74849374-b95bfa00-5360-11ea-9f2c-c973a8134954.png)

**Comment by puzancozzu** [comment]
#include<stdio.h>
#include<conio.h>
#include<string.h>
void main(){
    struct student{
        char name[20];
        int roll;
        int age;
        char gender[6];
    }s[100],temp;
    int n,i,j,k;
    FILE *fp;
    printf("\nEnter how many records you want to enter : ");
    scanf("%d",&n);
    fp=fopen("student.txt","wb+");
    for(i=0;i<n;i++){
        printf("Enter Name, Roll no, Age & Gender of student %d: ",i+1);
        scanf("%s%d%d%s",s[i].name,&s[i].roll,&s[i].age,s[i].gender);
    }
    for(i=0;i<n-1;i++){
        for(j=i+1;j<n;j++){
            if(strcmp(s[i].name,s[j].name)>0){
                temp=s[i];
                s[i]=s[j];
                s[j]=temp;
            }
        }
    }
    fwrite(&s,sizeof(s),n,fp);
    rewind(fp);
    fread(&s,sizeof(s),("(%d)",n),fp);
    printf("\nSorted (by names):\n");
    for(i=0;i<n;i++){
        printf("Name : %-10sRoll no : %-4dAge : %-3dGender : %-2s\n",s[i].name,s[i].roll,s[i].age,s[i].gender);
    }
    fclose(fp);
getch();
}
![1](https://user-images.githubusercontent.com/57807162/74857771-4789ad80-536c-11ea-884b-1b7a76754cae.PNG)
